INSERT INTO public.movie_user (id, display_name, password, username) VALUES (-1, 'Jason Skipper', 'mypass', 'jason');
INSERT INTO public.movie (id, category, description, mpaa_rating, name, poster_url, rating) VALUES (-1, 'Sci-Fi', 'A cool sci fi film', 'R', 'Matrix', 'https://www.movieposter.com/posters/archive/main/9/A70-4902', 10);
INSERT INTO public.movie (id, category, description, mpaa_rating, name, poster_url, rating) VALUES (-2, 'Sci-Fi', 'A coolish sci fi film', 'R', 'Matrix 1', 'http://vignette4.wikia.nocookie.net/thegamingfamily/images/0/07/The-Matrix-Reloaded-movie-poster.jpg/revision/latest?cb=20140922193256', 9.5);
INSERT INTO public.movie (id, category, description, mpaa_rating, name, poster_url, rating) VALUES (-3, 'Sci-Fi', 'A coolish sci fi film', 'R', 'Matrix 2', 'http://vignette4.wikia.nocookie.net/thegamingfamily/images/0/07/The-Matrix-Reloaded-movie-poster.jpg/revision/latest?cb=20140922193256', 9.5);
INSERT INTO public.movie (id, category, description, mpaa_rating, name, poster_url, rating) VALUES (-4, 'Sci-Fi', 'A coolish sci fi film', 'R', 'Matrix 3', 'http://vignette4.wikia.nocookie.net/thegamingfamily/images/0/07/The-Matrix-Reloaded-movie-poster.jpg/revision/latest?cb=20140922193256', 9.5);
INSERT INTO public.movie (id, category, description, mpaa_rating, name, poster_url, rating) VALUES (-5, 'Sci-Fi', 'A coolish sci fi film', 'R', 'Matrix 4', 'http://vignette4.wikia.nocookie.net/thegamingfamily/images/0/07/The-Matrix-Reloaded-movie-poster.jpg/revision/latest?cb=20140922193256', 9.5);
INSERT INTO public.movie (id, category, description, mpaa_rating, name, poster_url, rating) VALUES (-6, 'Sci-Fi', 'A coolish sci fi film', 'R', 'Matrix 5', 'http://vignette4.wikia.nocookie.net/thegamingfamily/images/0/07/The-Matrix-Reloaded-movie-poster.jpg/revision/latest?cb=20140922193256', 9.5);
INSERT INTO public.movie (id, category, description, mpaa_rating, name, poster_url, rating) VALUES (-7, 'Sci-Fi', 'A coolish sci fi film', 'R', 'Matrix 6', 'http://vignette4.wikia.nocookie.net/thegamingfamily/images/0/07/The-Matrix-Reloaded-movie-poster.jpg/revision/latest?cb=20140922193256', 9.5);
INSERT INTO public.movie (id, category, description, mpaa_rating, name, poster_url, rating) VALUES (-8, 'Sci-Fi', 'A coolish sci fi film', 'R', 'Matrix 7', 'http://vignette4.wikia.nocookie.net/thegamingfamily/images/0/07/The-Matrix-Reloaded-movie-poster.jpg/revision/latest?cb=20140922193256', 9.5);
